version: '3.8'

services:
  backend:
    build: ./backend
    container_name: django_backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    restart: unless-stopped

  frontend:
    build: ./backend
    container_name: vue_frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
