# Generated by Django 5.2.10 on 2026-06-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoDompet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entitas', models.CharField(choices=[('PT', 'PT (Utama)'), ('CV', 'CV (Sekunder)')], max_length=5)),
                ('kategori', models.CharField(choices=[('FISIK', 'Cash Fisik (Tunai / Kas Kecil)'), ('ELEKTRIK', 'Cash Elektrik (Bank / E-Wallet)'), ('PIUTANG', 'Piutang (Tagihan Klien Belum Lunas)')], max_length=15)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('terakhir_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'keuangan_saldo_dompet',
                'unique_together': {('entitas', 'kategori')},
            },
        ),
    ]
